services:
  hr-id-automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-id-automation
    ports:
      - "8005:8005"
    env_file:
      - .env
    restart: unless-stopped
